spring:
  application:
    name: websocket-app
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/chatapp}
    username: postgres
    password: cheistopher
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:9a4f4c35456545445258584850524b584e4b524b584e4b524b584e4b524b584e}
  expiration: 86400000 # 24 hours
